Feature Weather App
sergiocortessat/JSWeatherApp pull request #1
Opened 2021-06-02 17:33 UTC by sergiocortessat

Pull request 1 Weather app

2021-06-02 18:39 UTC, SajjadAhmad14 commented on src/dom.js
> +      realTempDiv.append(realTempName, realTempElement);
App logic should not be mixed with DOM manipulation.

2021-06-02 18:41 UTC, SajjadAhmad14 requested changes
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [x] You have mastered Git flow.
- [x] PR title and summary are descriptive.
- [x] App UI is pleasing.
## To Improve 🙏
- [ ] Please add the `npm install` command in your `Clone project` section of README. The project can not be installed and run without this command.
- [ ] LinkedIn link is not active in the `Authors` section. Please fix that.
- [ ] App logic should be separate from DOM manipulation tasks.
- [ ] async function should handle error so that it does not crash if an error occurs. Your app should show a friendly error when the user inputs an invalid city name.
- [ ] Please see inline comments for reference.
# Optional
- [ ] It's nice if the app fetches the current geolocation of the user when the it is first accessed and fetches the weather from that location
### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-06-03 11:21 UTC, sergiocortessat commented
Pull request 2

Hello TSE and thank you for checking on my project. I have implemented the requested changes to the repo such as:

- npm install command in your Clone project section of README.
- LinkedIn link has been fixed
- App logic was separated from DOM.
- The async function nows handle a pop up error

2021-06-03 12:42 UTC, NtwaliHeritier approved these changes
### **STATUS: APPROVED✔✔✔✔✔**

Hello @sergiocortessat 

Great work making the requested changes🙌👏👏
You can merge👌👍

Happy coding💻💻

2021-06-03 16:35 UTC, merged